// Auto-generated by Supabase. Regenerate after every migration:
// npx supabase gen types typescript --local > src/types/database.ts
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
